language: python
python:
  - "2.7"
  
# command to install dependencies
install: pip install Flask-SQLAlchemy Flask MYSQL-python flask-socketio Flask-Table python-dateutil coverage

before_script:
- mysql -e "CREATE DATABASE JP_Project"

# command to run tests
script: 
- python server_simulator.py & coverage run unit_test.py
- coverage report

services:
  - mysql
sudo: required
dist: trusty
cache: pip
