language: python
python:
  - "2.7"

# command to install dependencies
install: pip install Flask-SQLAlchemy Flask MYSQL-python flask-socketio
# command to run tests
script: server_simulator unit_test

sudo: required
dist: trusty
