language: python
python:
  - "2.7"

# command to install dependencies
install: pip install Flask-SQLAlchemy Flask MYSQL-python flask-socketio
# command to run tests
script: 
- python server_simulator.py
- python unit_test.py

sudo: required
dist: trusty
