language: python
python:
  - "2.7"
  
# command to install dependencies
install: pip install Flask-SQLAlchemy Flask MYSQL-python flask-socketio Flask-Table dateutil

before_script:
- mysql -e "CREATE DATABASE myapp_test"

# command to run tests
script: 
- python server_simulator.py
- python unit_test.py

services:
  - mysql
sudo: required
dist: trusty
