language: python
python:
  - "2.7"
  
# command to install dependencies
install: pip install Flask-SQLAlchemy Flask MYSQL-python flask-socketio Flask-Table python-dateutil coverage

before_script:
- mysql -u root -e "CREATE DATABASE JP_Project"
- sh -c "mysql -u root -e 'CREATE TABLE JP_Project.order (
    order_id int(11) NOT NULL PRIMARY KEY,
    totalVolume int(11) NOT NULL,
    uid int(11) NOT NULL,
    time DATETIME DEFAULT NULL,
    status int(11) DEFAULT 0
    );'"
 - sh -c "mysql -u root -e 'CREATE TABLE JP_Project.suborder (
    suborder_id int(11) NOT NULL PRIMARY KEY,
    status tinyint(4) NOT NULL,
    time datetime DEFAULT NULL,
    volume int(11) DEFAULT NULL,
    price decimal(5,2) DEFAULT NULL,
    order_id int(11) DEFAULT NULL
    );'"
 - sh -c "mysql -u root -e 'CREATE TABLE JP_Project.User (
    'uid' INT(11) NOT NULL AUTO_INCREMENT,
    'username' VARCHAR(45) NOT NULL,
    'password' VARCHAR(45) NOT NULL,
    PRIMARY KEY (`uid`),
    );'"
  - mysqlshow "JP_Project"

# command to run tests
script: 
- python server_simulator.py & coverage run unit_test.py
- coverage report

services:
  - mysql
sudo: required
dist: trusty
cache: pip
